import { Job, Application, ActivityItem } from "./types";
import { getAlignmentFromScore } from "./types";

export const mockJobs: Job[] = [
  {
    id: "job-1",
    title: "Application Support Engineer",
    companyName: "Infosys",
    location: "Noida",
    source: "LinkedIn",
    url: "https://linkedin.com/jobs/view/1",
    description:
      "## Application Support Engineer\n\nWe are looking for an experienced **Application Support Engineer** to join our team. You will be responsible for providing Level 2/3 support for enterprise applications, troubleshooting production issues, and collaborating with development teams.\n\n### Responsibilities\n- Monitor and maintain application health\n- Investigate and resolve production incidents\n- Work with L1 support for escalation\n- Automate routine operational tasks\n- Participate in on-call rotations\n\n### Requirements\n- 3-6 years of application support experience\n- Strong knowledge of Linux/Windows server administration\n- Experience with monitoring tools (Datadog, New Relic, Splunk)\n- Scripting skills in Python or Bash\n- SQL proficiency\n- Knowledge of CI/CD pipelines",
    matchScore: 85,
    alignment: "Strong Match",
    skills: [
      "Linux",
      "Python",
      "SQL",
      "Monitoring Tools",
      "CI/CD",
      "Bash",
      "Incident Management",
    ],
    experienceRange: "3-6 years",
    workMode: "Hybrid",
    datePosted: "2026-04-18",
    saved: false,
  },
  {
    id: "job-2",
    title: "DevOps Support Engineer",
    companyName: "TCS",
    location: "Delhi NCR",
    source: "Naukri",
    url: "https://naukri.com/job/2",
    description:
      "## DevOps Support Engineer\n\nJoin our DevOps team to manage and support cloud infrastructure and deployment pipelines.\n\n### Key Responsibilities\n- Manage AWS/Azure infrastructure\n- Support CI/CD pipelines\n- Container orchestration with Kubernetes\n- Infrastructure as Code using Terraform\n- Monitoring and alerting setup\n\n### Requirements\n- 4-7 years DevOps experience\n- AWS/Azure certifications preferred\n- Strong Kubernetes and Docker skills\n- Terraform/Ansible experience",
    matchScore: 72,
    alignment: "Strong Match",
    skills: [
      "AWS",
      "Kubernetes",
      "Docker",
      "Terraform",
      "CI/CD",
      "Python",
      "Monitoring",
    ],
    experienceRange: "4-7 years",
    workMode: "Remote",
    datePosted: "2026-04-19",
    saved: false,
  },
  {
    id: "job-3",
    title: "MFT Specialist",
    companyName: "Wipro",
    location: "Bangalore",
    source: "Web Search",
    url: "https://example.com/jobs/3",
    description:
      "## Managed File Transfer Specialist\n\nLooking for an MFT Specialist to manage and maintain our file transfer infrastructure.\n\n### Responsibilities\n- Administer IBM Sterling B2B Integrator\n- Manage SFTP/FTP file transfers\n- Implement secure file transfer protocols\n- Monitor transfer schedules and failures\n- Optimize transfer performance\n\n### Requirements\n- 3-5 years MFT experience\n- IBM Sterling B2B knowledge\n- Strong understanding of secure protocols\n- Scripting and automation skills",
    matchScore: 65,
    alignment: "Good Match",
    skills: [
      "IBM Sterling",
      "SFTP",
      "File Transfer",
      "Linux",
      "Scripting",
      "Security Protocols",
    ],
    experienceRange: "3-5 years",
    workMode: "Onsite",
    datePosted: "2026-04-17",
    saved: false,
  },
  {
    id: "job-4",
    title: "IT Infrastructure Support Lead",
    companyName: "HCL Technologies",
    location: "Noida",
    source: "LinkedIn",
    url: "https://linkedin.com/jobs/view/4",
    description:
      "## IT Infrastructure Support Lead\n\nLead a team of support engineers managing enterprise IT infrastructure.\n\n### Responsibilities\n- Lead L2/L3 infrastructure support team\n- Manage server infrastructure (physical & virtual)\n- Network troubleshooting and management\n- Capacity planning and optimization\n- Vendor management\n\n### Requirements\n- 6-10 years infrastructure experience\n- Team leadership experience\n- VMware/Hyper-V expertise\n- Network certifications (CCNA/CCNP preferred)",
    matchScore: 58,
    alignment: "Good Match",
    skills: [
      "VMware",
      "Networking",
      "Linux",
      "Windows Server",
      "Team Leadership",
      "Capacity Planning",
    ],
    experienceRange: "6-10 years",
    workMode: "Hybrid",
    datePosted: "2026-04-16",
    saved: false,
  },
  {
    id: "job-5",
    title: "Site Reliability Engineer",
    companyName: "Flipkart",
    location: "Bangalore",
    source: "Web Search",
    url: "https://example.com/jobs/5",
    description:
      "## Site Reliability Engineer\n\nWe need an SRE to ensure the reliability and scalability of our e-commerce platform.\n\n### Responsibilities\n- Design and maintain highly available systems\n- Build monitoring and alerting systems\n- Participate in on-call rotations\n- Conduct post-incident reviews\n- Automate operational tasks\n\n### Requirements\n- 3-6 years SRE/DevOps experience\n- Strong programming skills (Go/Python)\n- Kubernetes and container orchestration\n- Experience with large-scale distributed systems",
    matchScore: 48,
    alignment: "Good Match",
    skills: [
      "Go",
      "Kubernetes",
      "Docker",
      "Monitoring",
      "Python",
      "Distributed Systems",
      "AWS",
    ],
    experienceRange: "3-6 years",
    workMode: "Hybrid",
    datePosted: "2026-04-20",
    saved: false,
  },
  {
    id: "job-6",
    title: "Cloud Support Associate",
    companyName: "Accenture",
    location: "Remote",
    source: "Naukri",
    url: "https://naukri.com/job/6",
    description:
      "## Cloud Support Associate\n\nProvide technical support for cloud services and infrastructure.\n\n### Responsibilities\n- Support AWS/Azure/GCP services\n- Troubleshoot cloud infrastructure issues\n- Assist with cloud migrations\n- Document technical procedures\n- Provide training to junior staff\n\n### Requirements\n- 1-3 years cloud support experience\n- AWS Cloud Practitioner or equivalent\n- Basic Linux and networking skills\n- Good communication skills",
    matchScore: 35,
    alignment: "Stretch",
    skills: [
      "AWS",
      "Linux",
      "Cloud Migration",
      "Troubleshooting",
      "Azure",
    ],
    experienceRange: "1-3 years",
    workMode: "Remote",
    datePosted: "2026-04-15",
    saved: false,
  },
  {
    id: "job-7",
    title: "Linux System Administrator",
    companyName: "Tech Mahindra",
    location: "Jaipur",
    source: "Manual",
    url: "https://example.com/jobs/7",
    description:
      "## Linux System Administrator\n\nManage and maintain Linux server infrastructure for our enterprise clients.\n\n### Responsibilities\n- Server provisioning and configuration\n- Performance monitoring and tuning\n- Security patching and compliance\n- Backup and disaster recovery management\n- Script automation\n\n### Requirements\n- 3-5 years Linux administration\n- RHEL/CentOS/Ubuntu expertise\n- Shell scripting (Bash/Python)\n- Understanding of network protocols\n- Virtualization experience",
    matchScore: 42,
    alignment: "Stretch",
    skills: [
      "Linux",
      "Bash",
      "Python",
      "RHEL",
      "Virtualization",
      "Networking",
    ],
    experienceRange: "3-5 years",
    workMode: "Onsite",
    datePosted: "2026-04-14",
    saved: false,
  },
  {
    id: "job-8",
    title: "Database Administrator",
    companyName: "Oracle India",
    location: "Noida",
    source: "LinkedIn",
    url: "https://linkedin.com/jobs/view/8",
    description:
      "## Database Administrator\n\nManage Oracle and PostgreSQL databases for enterprise applications.\n\n### Responsibilities\n- Database installation and configuration\n- Performance tuning and optimization\n- Backup and recovery management\n- Data migration support\n- Security and access management\n\n### Requirements\n- 4-7 years DBA experience\n- Oracle 19c/21c expertise\n- PostgreSQL administration\n- RAC and Data Guard experience\n- Strong SQL and PL/SQL skills",
    matchScore: 25,
    alignment: "Stretch",
    skills: [
      "Oracle DB",
      "PostgreSQL",
      "SQL",
      "PL/SQL",
      "RAC",
      "Performance Tuning",
    ],
    experienceRange: "4-7 years",
    workMode: "Onsite",
    datePosted: "2026-04-13",
    saved: false,
  },
  {
    id: "job-9",
    title: "Cybersecurity Analyst",
    companyName: "Deloitte",
    location: "Delhi NCR",
    source: "Web Search",
    url: "https://example.com/jobs/9",
    description:
      "## Cybersecurity Analyst\n\nMonitor, detect, and respond to cybersecurity threats.\n\n### Responsibilities\n- Security event monitoring\n- Incident response and investigation\n- Vulnerability assessment\n- Security tool management (SIEM, IDS/IPS)\n- Compliance and audit support\n\n### Requirements\n- 2-4 years cybersecurity experience\n- SIEM tool experience (Splunk, QRadar)\n- CISSP or CEH certification preferred\n- Understanding of OWASP top 10",
    matchScore: 15,
    alignment: "Ignore",
    skills: [
      "SIEM",
      "Splunk",
      "Incident Response",
      "Vulnerability Assessment",
      "OWASP",
    ],
    experienceRange: "2-4 years",
    workMode: "Hybrid",
    datePosted: "2026-04-12",
    saved: false,
  },
  {
    id: "job-10",
    title: "Technical Support Engineer",
    companyName: "Paytm",
    location: "Noida",
    source: "Naukri",
    url: "https://naukri.com/job/10",
    description:
      "## Technical Support Engineer\n\nProvide technical support for payment platform and merchant integrations.\n\n### Responsibilities\n- L2/L3 technical support\n- Payment gateway troubleshooting\n- API debugging and support\n- Merchant onboarding assistance\n- Documentation and knowledge base maintenance\n\n### Requirements\n- 2-4 years technical support experience\n- REST API knowledge\n- Payment industry experience preferred\n- Good problem-solving skills",
    matchScore: 52,
    alignment: "Good Match",
    skills: [
      "REST APIs",
      "Troubleshooting",
      "Payment Systems",
      "Technical Support",
      "Documentation",
    ],
    experienceRange: "2-4 years",
    workMode: "Hybrid",
    datePosted: "2026-04-20",
    saved: false,
  },
  {
    id: "job-11",
    title: "Platform Engineer",
    companyName: "Zomato",
    location: "Bangalore",
    source: "LinkedIn",
    url: "https://linkedin.com/jobs/view/11",
    description:
      "## Platform Engineer\n\nBuild and maintain internal developer platforms and tools.\n\n### Responsibilities\n- Build self-service developer platforms\n- Container orchestration and service mesh\n- Implement GitOps workflows\n- Infrastructure automation\n- Developer experience improvement\n\n### Requirements\n- 3-5 years platform engineering\n- Kubernetes and Helm charts\n- ArgoCD/Flux experience\n- Programming in Go or Python",
    matchScore: 38,
    alignment: "Stretch",
    skills: [
      "Kubernetes",
      "Helm",
      "ArgoCD",
      "Go",
      "GitOps",
      "Platform Engineering",
    ],
    experienceRange: "3-5 years",
    workMode: "Hybrid",
    datePosted: "2026-04-19",
    saved: false,
  },
  {
    id: "job-12",
    title: "IT Operations Manager",
    companyName: "Cognizant",
    location: "Delhi NCR",
    source: "Web Search",
    url: "https://example.com/jobs/12",
    description:
      "## IT Operations Manager\n\nOversee IT operations and ensure service delivery for enterprise clients.\n\n### Responsibilities\n- Manage IT operations team\n- Ensure SLA compliance\n- Change management and release coordination\n- Vendor management\n- Budget planning and resource allocation\n\n### Requirements\n- 8-12 years IT experience\n- ITIL certification preferred\n- Team management experience\n- Strong stakeholder management",
    matchScore: 12,
    alignment: "Ignore",
    skills: [
      "ITIL",
      "IT Operations",
      "Team Management",
      "SLA Management",
      "Vendor Management",
    ],
    experienceRange: "8-12 years",
    workMode: "Onsite",
    datePosted: "2026-04-11",
    saved: false,
  },
  {
    id: "job-13",
    title: "Automation Testing Engineer",
    companyName: "Capgemini",
    location: "Jaipur",
    source: "Manual",
    url: "https://example.com/jobs/13",
    description:
      "## Automation Testing Engineer\n\nDesign and implement test automation frameworks for enterprise applications.\n\n### Responsibilities\n- Design test automation frameworks\n- Write and maintain automated test scripts\n- Integration with CI/CD pipelines\n- Performance testing and load testing\n- Test reporting and analytics\n\n### Requirements\n- 3-5 years testing experience\n- Selenium/Cypress expertise\n- Java/Python programming\n- API testing (Postman/REST Assured)\n- Performance testing (JMeter)",
    matchScore: 22,
    alignment: "Stretch",
    skills: [
      "Selenium",
      "Python",
      "Java",
      "API Testing",
      "CI/CD",
      "JMeter",
    ],
    experienceRange: "3-5 years",
    workMode: "Hybrid",
    datePosted: "2026-04-10",
    saved: false,
  },
  {
    id: "job-14",
    title: "L2 Support Engineer - Enterprise Apps",
    companyName: "Mindtree",
    location: "Noida",
    source: "LinkedIn",
    url: "https://linkedin.com/jobs/view/14",
    description:
      "## L2 Support Engineer\n\nProvide Level 2 support for enterprise applications and middleware.\n\n### Responsibilities\n- Application troubleshooting and resolution\n- Middleware administration (WebLogic, Tomcat)\n- Database query tuning\n- Coordinate with L3 and development teams\n- Create and update knowledge articles\n\n### Requirements\n- 2-5 years application support\n- Java/J2EE understanding\n- WebLogic/Tomcat experience\n- SQL and database knowledge\n- ITSM tools (ServiceNow)",
    matchScore: 78,
    alignment: "Strong Match",
    skills: [
      "Java",
      "WebLogic",
      "SQL",
      "ServiceNow",
      "Troubleshooting",
      "Linux",
      "Middleware",
    ],
    experienceRange: "2-5 years",
    workMode: "Onsite",
    datePosted: "2026-04-20",
    saved: false,
  },
  {
    id: "job-15",
    title: "Senior DevOps Engineer",
    companyName: "Microsoft India",
    location: "Hyderabad",
    source: "Web Search",
    url: "https://example.com/jobs/15",
    description:
      "## Senior DevOps Engineer\n\nLead DevOps practices and cloud transformation initiatives.\n\n### Responsibilities\n- Design and implement CI/CD pipelines\n- Cloud infrastructure management\n- Team mentoring and best practices\n- Cost optimization\n- Security and compliance automation\n\n### Requirements\n- 6-10 years DevOps experience\n- Azure/AWS multi-cloud expertise\n- Strong programming background\n- Leadership and mentoring skills",
    matchScore: 55,
    alignment: "Good Match",
    skills: [
      "Azure",
      "AWS",
      "Kubernetes",
      "Terraform",
      "Python",
      "Leadership",
      "CI/CD",
    ],
    experienceRange: "6-10 years",
    workMode: "Hybrid",
    datePosted: "2026-04-18",
    saved: false,
  },
];

export const mockApplications: Application[] = [
  {
    id: "app-1",
    jobId: "job-1",
    jobTitle: "Application Support Engineer",
    companyName: "Infosys",
    status: "applied",
    appliedDate: "2026-04-15",
  },
  {
    id: "app-2",
    jobId: "job-2",
    jobTitle: "DevOps Support Engineer",
    companyName: "TCS",
    status: "interviewing",
    appliedDate: "2026-04-12",
  },
  {
    id: "app-3",
    jobId: "job-14",
    jobTitle: "L2 Support Engineer - Enterprise Apps",
    companyName: "Mindtree",
    status: "interested",
    appliedDate: "2026-04-20",
  },
  {
    id: "app-4",
    jobId: "job-3",
    jobTitle: "MFT Specialist",
    companyName: "Wipro",
    status: "applied",
    appliedDate: "2026-04-14",
  },
  {
    id: "app-5",
    jobId: "job-10",
    jobTitle: "Technical Support Engineer",
    companyName: "Paytm",
    status: "interested",
    appliedDate: "2026-04-19",
  },
  {
    id: "app-6",
    jobId: "job-4",
    jobTitle: "IT Infrastructure Support Lead",
    companyName: "HCL Technologies",
    status: "offered",
    appliedDate: "2026-04-05",
  },
  {
    id: "app-7",
    jobId: "job-5",
    jobTitle: "Site Reliability Engineer",
    companyName: "Flipkart",
    status: "applied",
    appliedDate: "2026-04-16",
  },
  {
    id: "app-8",
    jobId: "job-15",
    jobTitle: "Senior DevOps Engineer",
    companyName: "Microsoft India",
    status: "interested",
    appliedDate: "2026-04-17",
  },
];

export const mockActivities: ActivityItem[] = [
  {
    id: "act-1",
    type: "search",
    description: "Searched for Application Support jobs in Noida",
    timestamp: "2026-04-20T10:30:00Z",
  },
  {
    id: "act-2",
    type: "apply",
    description: "Applied to Application Support Engineer at Infosys",
    timestamp: "2026-04-19T14:15:00Z",
  },
  {
    id: "act-3",
    type: "interview",
    description: "Interview scheduled with TCS for DevOps Support Engineer",
    timestamp: "2026-04-19T09:00:00Z",
  },
  {
    id: "act-4",
    type: "save",
    description: "Saved 3 jobs from LinkedIn search results",
    timestamp: "2026-04-18T16:45:00Z",
  },
  {
    id: "act-5",
    type: "score",
    description: "Match analysis completed for 12 new job listings",
    timestamp: "2026-04-18T11:20:00Z",
  },
  {
    id: "act-6",
    type: "search",
    description: "Searched for DevOps Engineer roles in Delhi NCR",
    timestamp: "2026-04-17T08:30:00Z",
  },
  {
    id: "act-7",
    type: "apply",
    description: "Applied to MFT Specialist at Wipro",
    timestamp: "2026-04-16T13:00:00Z",
  },
  {
    id: "act-8",
    type: "interview",
    description: "Received interview invite from HCL Technologies",
    timestamp: "2026-04-15T10:00:00Z",
  },
];

export function getUniqueCompanies(jobs: Job[]): string[] {
  return [...new Set(jobs.map((j) => j.companyName))];
}

export function getStats(jobs: Job[], applications: Application[]) {
  return {
    totalJobs: jobs.length,
    strongMatches: jobs.filter((j) => (j.matchScore ?? 0) >= 70).length,
    activeApplications: applications.filter(
      (a) => a.status !== "completed"
    ).length,
    companiesTargeted: getUniqueCompanies(jobs).length,
  };
}

export function getPipelineCounts(applications: Application[]) {
  const stages = ["interested", "applied", "interviewing", "offered"] as const;
  return stages.map((stage) => ({
    stage: stage.charAt(0).toUpperCase() + stage.slice(1),
    count: applications.filter((a) => a.status === stage).length,
  }));
}
